# Site settings
title: sagarkar10
email: sagarkar10@gmail.com
url: https://sagarkar10.github.io
description: "by Sagar Kar , This is my personal website created from opensource stuffs."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: sagarkar10

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/sagarkar10
  - title: facebook
    url:https://www.facebook.com/sagarkar10
  - title: stack-overflow
    url: http://stackoverflow.com/users/4192965/sagar-kar
  - title: linkedin
    url: https://in.linkedin.com/in/sagarkar10
  - title: github
    url: https://github.com/sagarkar10

# Build settings
markdown: kramdown
permalink: pretty
